@url=http://localhost:8000

### user

### Get all users 
GET {{url}}/users
### Create a new user
POST {{url}}/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@gmail.com",
    "password": "password123",
    "isActive": true,
    "profile": {
        "Id":"12345",
        "bio": "Software Engineer",
        "avatar": "https://example.com/avatar.jpg",
        "dateOfBirth": "1990-01-01"
    }
}
### Get a user by ID
GET {{url}}/users/1
### Update a user by ID
PUT {{url}}/users/7
Content-Type: application/json

{
    "name": "sam Doe Updated",
    "email": "doe@gmail.com",
    "password": "newpassword123",
    "isActive": false,
    "profile": {
        "bio": "Senior Software Engineer",
        "avatar": "https://example.com/avatar_updated.jpg",
        "dateOfBirth": "1990-01-01"
    }
}

### Delete a user by ID
DELETE {{url}}/users/1
### PROFILE
### Get all profiles
GET {{url}}/profiles
### Create a new profile
POST {{url}}/profiles
Content-Type: application/json

{
    "bio": "Software Dveloper",
    "avatar": "https://example.com/avatar.jpg",
    "dateOfBirth": "1990-01-01"
}
### Get a profile by ID
GET {{url}}/profiles/5
### Update a profile by ID
PUT {{url}}/profiles/5
Content-Type: application/json

{
    "bio": "Senior Software Dveloper",
    "avatar": "https://example.com/avatar_updated.jpg",
    "dateOfBirth": "1990-01-01"
}
### Delete a profile by ID
DELETE {{url}}/profiles/5 

### AUTHOR
### Get all authors
GET {{url}}/authors
### Create a new author
POST {{url}}/authors
Content-Type: application/json

{
    "authorId": "109",
    "name": "F. Scott Fitzgerald",
    "bio": "An American novelist and short story writer.",
    "isActive": true,
    "birthDate": "1896-09-24"
}
### Get an author by ID
GET {{url}}/authors/109
### Update an author by ID
PUT {{url}}/authors/109
Content-Type: application/json

{
    "name": "F. Scott Fitzgerald Updated",
    "bio": "An American novelist and short story writer, known for his novel 'The Great Gatsby'.",
    "isActive": false,
    "birthDate": "1896-09-24"
}
### Delete an author by ID
DELETE {{url}}/authors/109
###BOOKS
### Get all books
GET {{url}}/books 
### Create a new book
POST {{url}}/books
Content-Type: application/json

{
    "title": "The Great Gatsby",
   "description": "A novel written by American author F. Scott Fitzgerald.",
   "publicationYear":"1925",
   "isAvailable": true,
   "authorId": "101"
}
### Get a book by ID
GET {{url}}/books/1

###update a book by an id
PUT {{url}}/books/1
Content-Type: application/json

{
    "title": "The Great Gatsby Updated",
    "description": "A novel written by American author F. Scott Fitzgerald, updated edition.",
    "publicationYear": "1925",
    "isAvailable": false,
    "authorId": "101"
}
### Delete a book by ID
DELETE {{url}}/books/2
### Get all books by author ID
GET {{url}}/authors/101/books
###categories
### Get all categories
GET {{url}}/categories
### Create a new category
POST {{url}}/categories
Content-Type: application/json

{
    "name": "Fiction",
    "description": "A category for fictional books."
}
### Get a category by ID
GET {{url}}/categories/1
### Update a category by ID
PUT {{url}}/categories/1
Content-Type: application/json

{
    "name": "Fiction Updated",
    "description": "A category for fictional books, updated description."
}
### Delete a category by ID
DELETE {{url}}/categories/1
### Get all books in a category
GET {{url}}/categories/1/books
### Get all books by category ID
GET {{url}}/books?categoryId=1
#### bookreviews
### Get all book reviews    
GET {{url}}/bookreviews
### Create a new book review
POST {{url}}/bookreviews
Content-Type: application/json

{
   "content": "An insightful review of The Great Gatsby.",
   "createdAt":"",
   "rating": 5,
    "bookId": "1",
    "userId": "7"
}

