@url=http://localhost:8000

### user

### Get all users 
GET {{url}}/users
### Create a new user
POST {{url}}/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@gmail.com",
    "password": "password123",
    "isActive": true,
    "profile": {
        "Id":"12345",
        "bio": "Software Engineer",
        "avatar": "https://example.com/avatar.jpg",
        "dateOfBirth": "1990-01-01"
    }
}
### Get a user by ID
GET {{url}}/users/1
### Update a user by ID
PUT {{url}}/users/1
Content-Type: application/json

{
    "name": "sam Doe Updated",
    "email": "doe@gmail.com",
    "password": "newpassword123",
    "isActive": false,
    "profile": {
        "Id":"12345",
        "bio": "Senior Software Engineer",
        "avatar": "https://example.com/avatar_updated.jpg",
        "dateOfBirth": "1990-01-01"
    }
}

### Delete a user by ID
DELETE {{url}}/users/1
### PROFILE
### Get all profiles
GET {{url}}/profiles
### Create a new profile
POST {{url}}/profiles
Content-Type: application/json

{
    "Id": "333",
    "bio": "Software Dveloper",
    "avatar": "https://example.com/avatar.jpg",
    "dateOfBirth": "1990-01-01"
}
### Get a profile by ID
GET {{url}}/profiles/5
### Update a profile by ID
PUT {{url}}/profiles/5
Content-Type: application/json

{
    "bio": "Senior Software Dveloper",
    "avatar": "https://example.com/avatar_updated.jpg",
    "dateOfBirth": "1990-01-01"
}
### Delete a profile by ID
DELETE {{url}}/profiles/5 

### AUTHOR
### Get all authors
GET {{url}}/authors
### Create a new author
POST {{url}}/authors
Content-Type: application/json

{
    "authorId": "222",
    "name": "F. Scott Fitzgerald",
    "bio": "An American novelist and short story writer.",
    "isActive": true,
    "birthDate": "1896-09-24"
}
### Get an author by ID
GET {{url}}/authors/123
### Update an author by ID
PUT {{url}}/authors/123
Content-Type: application/json

{
    "name": "F. Scott Fitzgerald Updated",
    "bio": "An American novelist and short story writer, known for his novel 'The Great Gatsby'.",
    "isActive": false,
    "birthDate": "1896-09-24"
}
### Delete an author by ID
DELETE {{url}}/authors/123
###BOOKS
### Get all books
GET {{url}}/books 
### Create a new book
POST {{url}}/books
Content-Type: application/json

{
    "title": "The Great Gatsby",
   "description": "A novel written by American author F. Scott Fitzgerald.",
   "publishedYear": 1925,
   "isAvailable": true,
   "author": {
       "name": "F. Scott Fitzgerald",
       "birthdate": "1896-09-24"
       }
}

